name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  # Build job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Libxy (used by some tests)
        uses: actions/checkout@v4
        with:
          repository: xy-org/libxy
          path: 'tests/end_to_end_deps/libxy'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt -e .
      - name: Run Tests
        run: pytest -vv
