name: Build, Package, and Deploy Pyxyc

permissions:
  contents: write
  id-token: write
  deployments: write

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    # run on oldest possible version in order to guarantee maximum libc compatibility
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt -e .
      - name: Build and Package
        run: ./compile-and-package.sh
      - name: Release
        id: deployment
        uses: softprops/action-gh-release@v2
        with:
          files: xyc-*.tar.gz
          name: Continuous
          tag_name: continuous
