name: Build, Package, and Deploy Pyxyc

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements-dev.txt -e .
      - name: Build and Package
        run: ./compile-and-package.sh
      - name: Release
        id: deployment
        uses: softprops/action-gh-release@v2
        with:
          files: bin/xyc
          name: continuous

  # Deployment job
  deploy:
    environment:
      name: github-releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
